//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_ASP.NET_Final_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string mssg { get; set; }
        public System.DateTime DateM { get; set; }
    }
}
